"""
GymOps report generator.

Generates the weekly CI Workout Digest as a Markdown file.
This file is published as a GitHub Actions artifact named 'ci-workout-digest'.
"""

from datetime import date, timedelta
from pathlib import Path

from gymops.db import get_all_prs, get_weekly_digest_stats


def generate_digest(days: int = 7, output_dir: Path = Path(".")) -> str:
    """
    Generate a Markdown digest of recent workout activity using database views.

    Scans the last N days of workout history using database views, counts total sets logged,
    lists new/updated PRs during the period, and writes a Markdown file.

    Args:
        days: Number of days to include in the digest window.
        output_dir: Directory where the digest file will be written.

    Returns:
        The filename of the generated digest (e.g., 'digest_2026-06-22.md').
    """
    today = date.today()
    since = today - timedelta(days=days)
    filename = f"digest_{today.isoformat()}.md"
    output_path = output_dir / filename

    stats = get_weekly_digest_stats(days=days)
    all_prs = get_all_prs()

    total_sets = sum(item["sets_logged"] for item in stats)
    exercises_count = len(stats)

    # Build the Markdown content
    lines: list[str] = [
        "# GymOps CI Workout Digest",
        "",
        (
            f"**Period:** {since.isoformat()} → "
            f"{today.isoformat()} ({days} days)  "
        ),
        f"**Total Sets Logged:** {total_sets}  ",
        f"**Exercises Trained:** {exercises_count}  ",
        "",
        "---",
        "",
        "## 📊 Workout Summary",
        "",
        "| Exercise | Sets Logged | Best Weight (kg) | Best Est. 1RM (kg) |",
        "|:---------|------------:|-----------------:|-------------------:|",
    ]

    for item in stats:
        lines.append(
            f"| {item['exercise_name']} | {item['sets_logged']} | {item['best_weight']:.1f} | {item['best_1rm']:.1f} |"
        )

    lines += [
        "",
        "---",
        "",
        "## 🏆 Personal Records",
        "",
    ]

    if all_prs:
        lines += [
            "| Exercise | Max Weight (kg) | Est. 1RM (kg) | Date |",
            "|:---------|----------------:|--------------:|-----:|",
        ]
        for pr in all_prs:
            lines.append(
                f"| {pr.exercise_name} | {pr.max_weight:.1f} | "
                f"{pr.max_epley_1rm:.1f} | {str(pr.timestamp)[:10]} |"
            )
    else:
        lines.append("_No personal records set yet._")

    lines += [
        "",
        "---",
        "",
        f"_Generated by GymOps on {today.isoformat()}_",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return filename
